const QUESTIONS = [
  { id: 1, sentence: "A good policy is to always ___ to customer requests within 24 hours. Otherwise, they tend to Become annoyed and may find other providers.", answers: ["respond"] },
  { id: 2, sentence: "The department is responsible for the mistake so they will have to ___ the cost of the failure Themselves.", answers: ["pay"] },
  { id: 3, sentence: "We offer our customers the ___ of placing orders by phone or online.", answers: ["service"] },
  { id: 4, sentence: "I'm sorry I'm late. I ___ up late this morning.", answers: ["woke"] },
  { id: 5, sentence: "How much does the necklace ___? I don't see a price.", answers: ["cost"] },
  { id: 6, sentence: "The bill wasn't right. I think they ___ a mistake.", answers: ["made"] },
  { id: 7, sentence: "To ___ our first major success, we're going to throw a party.", answers: ["celebrate"] },
  { id: 8, sentence: "Before you drive over the bridge you have to pay the ___ at the booth.", answers: ["tax"] },
  { id: 9, sentence: "The company ___ its target last year and reported a profit.", answers: ["hit"] },
  { id: 10, sentence: "Please check all envelopes for the correct ___ address.", answers: ["return"] },
  { id: 11, sentence: "My ___ are ringing because the music was so loud at the concert.", answers: ["ears"] },
  { id: 12, sentence: "I had to take out a ___ from the bank to cover the cost of replacing the roof of my house.", answers: ["loan"] },
  { id: 13, sentence: "The training program ___ a wide selection of courses to any interested employee at a Minimum charge.", answers: ["offers", "includes"] },
  { id: 14, sentence: "It ___ to be seen whether the company will stay in business next year.", answers: ["has"] },
  { id: 15, sentence: "Should I turn ___ or left at the next corner?", answers: ["right"] },
  { id: 16, sentence: "I'm a salesman. And you, what do you ___?", answers: ["do"] },
  { id: 17, sentence: "She gets her supplies at a ___ rate because she buys in bulk.", answers: ["low"] },
  { id: 18, sentence: "This is cutting ___ technology it's the best on the market.", answers: ["edge"] },
  { id: 19, sentence: "Today is Tuesday. Yesterday was ___.", answers: ["Monday"] },
  { id: 20, sentence: "___ making one last modification to the layout, the newsletter was ready to be sent out.", answers: ["After"] },
  { id: 21, sentence: "Finally, everything I had to do is finished now that the project has reached ___.", answers: ["end"] },
  { id: 22, sentence: "What ___ is it? I don't have a watch.", answers: ["time"] },
  { id: 23, sentence: "Can you turn the lights ___? I can't see anything.", answers: ["ON"] },
  { id: 24, sentence: "When it rains, there are dark ___ in the sky.", answers: ["clouds"] },
  { id: 25, sentence: "An increasing ___ of the businesses have recently shut down due to the economic downturn.", answers: ["numbers"] },
  { id: 26, sentence: "The product is out of stock until the next ___ arrives.", answers: ["stock", "season", "shipment", "wave"] },
  { id: 28, sentence: "I went shopping yesterday and spent all my ___.", answers: ["money"] },
  { id: 29, sentence: "The store had only been in business for two months when the ___ sold it.", answers: ["owner"] },
  { id: 30, sentence: "The employees of our factory must follow a strict set of safety ___.", answers: ["protocols"] },
  { id: 31, sentence: "My friend, who has lived in New York all his life, took me a personal ___ of the city.", answers: ["tour"] },
  { id: 32, sentence: "The number of attendees far exceeded our expectation. The event site was very ___; it was not even easy to walk around.", answers: ["crowded"] },
  { id: 33, sentence: "How many languages can you ___?", answers: ["speak"] },
  { id: 34, sentence: "I don't have my credit card. I must have ___ it at home.", answers: ["kept", "left"] },
  { id: 35, sentence: "It looks like this document has been edited already – is this the final ___?", answers: ["copy"] },
  { id: 36, sentence: "The new trainees are ___ along just fine.", answers: ["going", "working"] },
  { id: 37, sentence: "She ran to the corner, but she just ___ the bus, so she had to wait for the next one.", answers: ["missed"] },
  { id: 38, sentence: "If you want to meet with the CEO, you need to make an ___ weeks in advance.", answers: ["appointment"] },
  { id: 39, sentence: "He's so concerned for the environment that I wasn't surprised when he told me the soles of his shoes were made out of ___ old tires.", answers: ["his"] },
  { id: 40, sentence: "If you don't ___ the height requirement, you are not allowed to get on the ride.", answers: ["fulfill"] },
  { id: 41, sentence: "Negotiations came to a halt as leaders struggled to reach terms that were ___ to both parties.", answers: ["acceptable"] },
  { id: 42, sentence: "He's running ___; he should have been here an hour ago.", answers: ["late"] },
  { id: 43, sentence: "When my bicycle got a flat ___, I had to take the train to work.", answers: ["tyre"] },
  { id: 44, sentence: "We had planned to go hiking today, but the weather was so bad that we had to come up with an ___ plan.", answers: ["alternate"] },
  { id: 45, sentence: "There was a clear blue sky and the sun was ___.", answers: ["bright"] },
  { id: 46, sentence: "In cities with good public ___, it's hard to understand why people insist on driving themselves to work.", answers: ["transportation"] },
  { id: 47, sentence: "Workers who have previously completed training are ___ from the new training requirements.", answers: ["exempted"] },
  { id: 48, sentence: "I ___ my clothes off at the dry cleaner on my way to work this morning.", answers: ["dropped"] },
  { id: 49, sentence: "Please make sure that all seatbelts are securely ___.", answers: ["fastened"] },
  { id: 50, sentence: "The company ___ its target last year and reported a profit.", answers: ["hit"] },
  { id: 51, sentence: "It is so bright and clear today. There isn't a ___ in the sky.", answers: ["cloud"] },
  { id: 52, sentence: "I highly ___ her for the job because she is intelligent and attentive.", answers: ["recommend"] },
  { id: 53, sentence: "To ___ Dan's birthday, his friends are going to have a party.", answers: ["celebrate"] },
  { id: 54, sentence: "She was ___ from the New York branch to the Los Angeles branch.", answers: ["transferred"] },
  { id: 55, sentence: "Is this dress available in a smaller ___? This one too big.", answers: ["size"] },
  { id: 56, sentence: "He arrived at the airport late, and ___ his flight, so he had to travel the next day.", answers: ["missed"] },
  { id: 57, sentence: "To avoid the danger from high wind, everyone was told to leave town ___ the hurricane arrived.", answers: ["before"] },
  { id: 58, sentence: "I went on a ___ of London on a double-decker bus to go sightseeing.", answers: ["tour"] },
  { id: 59, sentence: "You're driving too ___; you should slow down.", answers: ["fast"] },
  { id: 60, sentence: "I haven't eaten anything all day. I'm so ___.", answers: ["hungry"] },
  { id: 61, sentence: "She was awarded a promotion based on her excellent ___ on the job.", answers: ["performance"] },
  { id: 62, sentence: "It was so ___ outside that no one wanted to leave the air-conditioned house.", answers: ["hot"] },
  { id: 63, sentence: "You may not ___ with his method, but there's no question that he makes a lot of money for the company.", answers: ["agree"] },
  { id: 64, sentence: "I'm not sure I can come tomorrow. I'll have to ___ my schedule.", answers: ["check"] },
  { id: 65, sentence: "Some people wear ___ to help them see better.", answers: ["glasses"] },
  { id: 66, sentence: "The elevator is broken, so you will have to take the ___ to get to the second floor.", answers: ["stairs"] },
  { id: 67, sentence: "___ is my jacket? I can't find it.", answers: ["Where"] },
  { id: 68, sentence: "The money was ___ amongst several people.", answers: ["shared"] },
  { id: 69, sentence: "For ___ about the product, please consult the instruction manual.", answers: ["information"] },
  { id: 70, sentence: "I have trouble ___ at night, so I usually wake up very tired.", answers: ["sleeping"] },
  { id: 71, sentence: "Over three hundred people ___ the store's grand opening.", answers: ["attended"] },
  { id: 72, sentence: "I wanted to buy the book, but the bookstore didn't have any in ___. They expect to receive more next week.", answers: ["stock"] },
  { id: 73, sentence: "The class had to be ___ indefinitely because of the summer schedule.", answers: ["postponed"] },
  { id: 74, sentence: "You can ___ your order as soon as you know what you want to purchase.", answers: ["place"] },
  { id: 75, sentence: "Thank you very much for your help on such short ___. It helped us immensely when time was running out.", answers: ["notice"] },
  { id: 76, sentence: "The training program ___ a wide selection of courses to any interested employee at a minimum charge.", answers: ["includes"] },
  { id: 77, sentence: "Can I bring you something to ___? Perhaps tea or coffee?", answers: ["drink"] },
  { id: 78, sentence: "My ___ is very small. There's just my mother, father, and me.", answers: ["house"] },
  { id: 79, sentence: "The city can be divided into two parts. The outer sections are ___ new, while the historical city center is rather old, indeed.", answers: ["rarely"] },
  { id: 80, sentence: "When traveling in a foreign country, you should always carry your passport or some form of ___.", answers: ["identification", "identification card", "id"] },
  { id: 81, sentence: "The speaker at the conference was very interesting. I ___ his talk very much.", answers: ["liked"] },
  { id: 82, sentence: "I was recently ___ from the Berlin office to the Tokyo office.", answers: ["transferred"] },
  { id: 83, sentence: "Don't forget to ___ for a receipt when you pay.", answers: ["ask"] },
  { id: 84, sentence: "Since you've finished everything else, for the ___ of the week please focus your attention on finishing the expense reports.", answers: ["rest"] },
  { id: 85, sentence: "I don't ___ what I wrote. I'm going to rewrite it completely.", answers: ["understand"] },
  { id: 86, sentence: "The residents were advised to evacuate their homes ___ the storm reached them.", answers: ["before"] },
  { id: 87, sentence: "Recent studies have shown that the shopping ___ of consumers have changed dramatically in the past ten years.", answers: ["habits"] },
  { id: 88, sentence: "Although sales were down last quarter, the owner had high ___ that business would improve soon.", answers: ["expectations"] },
  { id: 89, sentence: "I know you love traveling abroad. Would you be ___ to take a position in our overseas office?", answers: ["able"] },
  { id: 90, sentence: "I couldn't believe it when he agreed to make an ___ on the show tonight.", answers: ["entry"] },
  { id: 91, sentence: "I need to write your first name. How do you ___ it?", answers: ["spell"] },
  { id: 92, sentence: "The man ___ his car keys and spent an hour looking for them this morning.", answers: ["lost"] },
  { id: 93, sentence: "My flight departed ten minutes later than scheduled but arrived on ___ at the destination.", answers: ["time"] },
  { id: 94, sentence: "She was a junior manager, but now she has been ___ to a senior management position.", answers: ["promoted"] },
  { id: 95, sentence: "A recent survey found that gadgets like phones and other small electronic ___ are very popular among online shoppers.", answers: ["devices"] },
  { id: 96, sentence: "Let's ___ tomorrow's presentation until next week.", answers: ["postpone"] },
  { id: 97, sentence: "The amount of air pollution in this town has increased substantially ___ the factory opened.", answers: ["since"] },
  { id: 98, sentence: "In my company, it is the manager's job to divide work ___ the team members.", answers: ["among"] },
  { id: 99, sentence: "Because of the sale, the bookstore didn't have any more televisions in ___, but they will get another delivery tomorrow.", answers: ["stock"] },
  { id: 100, sentence: "To get the new product, you can ___ your order online or over the telephone.", answers: ["place"] },
  { id: 101, sentence: "I'm sorry to inform you of this at such short ___, but everyone is going to need to work late tonight.", answers: ["notice"] },
  { id: 102, sentence: "Their wedding photographer was an ___, not a professional; all of their photographs turned out badly.", answers: ["amateur"] },
  { id: 103, sentence: "There has been peace ___ the two nations since they signed the international treaty.", answers: ["between"] },
  { id: 104, sentence: "We thought she would be ___ about going abroad, but she seemed completely bored.", answers: ["excited"] },
  { id: 105, sentence: "The company was having cash flow problems and had to take a ___ from the bank.", answers: ["loan"] },
  { id: 106, sentence: "The product is out of stock until the next ___ arrives.", answers: ["shipment"] },
  { id: 107, sentence: "He is suffering ___ a strange illness and has been in the hospital for three weeks.", answers: ["from"] },
  { id: 108, sentence: "The woman ___ her eyeglasses and had to buy a new pair.", answers: ["lost"] },
  { id: 109, sentence: "For more ___ about the job, please see the advertisement.", answers: ["information"] },
  { id: 110, sentence: "The return ___ needs to be provided on the letter.", answers: ["address"] },
  { id: 111, sentence: "We need to touch ___. So give me a call tomorrow.", answers: ["base"] },
  { id: 112, sentence: "Even though she failed her last driving test, she had high ___ that she would pass this time.", answers: ["hopes"] },
  { id: 113, sentence: "They ___ a mistake in how they spelled my name.", answers: ["made"] },
  { id: 114, sentence: "The company caused the pollution, so they need to ___ the cost of the cleanup themselves.", answers: ["cover"] },
  { id: 115, sentence: "Employees will lose pay accordingly if they are ___ to work", answers: ["late"] },
];